
scannerConfigurations:

  301:
    process_key   : "Process_Pallet_putaway"
    pallet_expiry_threshold: "10"
    dim_fail      : "DIM_FAIL"
    weigh_fail    : "WEIGH_FAIL"
    other_fail    : "ASRS_UNKN"
    container_fail: "ASRS_UNKN"
    pallet_unknown: "ASRS_UNKN"
    pallet_expired: "EXP_PALLET"
    asrs_full     : "ASRS_FULL"
    recall_reject : "RECALL_REJECT"
    robo_depal    : "ROBO_DEPAL"
    manual_depal  : "MANL_DEPAL"
  880:
    process_key   : "Process_Case_putaway"
    dim_fail      : "DIM_FAIL"
    weigh_fail    : "WEIGH_FAIL"
    other_fail    : "SHUTTLE_REJECT"
    container_fail: "SHUTTLE_REJECT"
    panda         : "PANDA"
    case_unknown  : "CASE_UNKN"
  890:
    process_key   : "Process_aisle_scanner_putaway"
    dim_fail      : "SH_REJECT_08"
    weigh_fail    : "SH_REJECT_08"
    other_fail    : "SH_REJECT_08"
    container_fail: "SH_REJECT_08"
    case_unknown  : "SH_REJECT_08"
    asrs_full     : "SH_REJECT_08"
    aisle 		  :
                    - name          : "SH_AISLE_U7"
                      level         :
                                      - "11"
                                      - "12"
                                      - "13"
                                      - "14"
                                      - "15"
                                      - "16"
                                      - "17"
                                      - "18"
                                      - "19"
                                      - "20"
                    - name          : "SH_AISLE_U8"
                      level         :
                                      - "11"
                                      - "12"
                                      - "13"
                                      - "14"
                                      - "15"
                                      - "16"
                                      - "17"
                                      - "18"
                                      - "19"
                                      - "20"
  889:
    process_key   : "Process_aisle_scanner_putaway"
    dim_fail      : "SH_REJECT_07"
    weigh_fail    : "SH_REJECT_07"
    other_fail    : "SH_REJECT_07"
    container_fail: "SH_REJECT_07"
    case_unknown  : "SH_REJECT_07"
    asrs_full     : "SH_REJECT_07"
    aisle 		  :
                    - name          : "SH_AISLE_L7"
                      level         :
                                      - "1"
                                      - "2"
                                      - "3"
                                      - "4"
                                      - "5"
                                      - "6"
                                      - "7"
                                      - "8"
                                      - "9"
                                      - "10"
                    - name          : "SH_AISLE_L8"
                      level         :
                                      - "1"
                                      - "2"
                                      - "3"
                                      - "4"
                                      - "5"
                                      - "6"
                                      - "7"
                                      - "8"
                                      - "9"
                                      - "10"
  886:
    process_key   : "Process_aisle_scanner_putaway"
    dim_fail      : "SH_REJECT_05"
    weigh_fail    : "SH_REJECT_05"
    other_fail    : "SH_REJECT_05"
    container_fail: "SH_REJECT_05"
    case_unknown  : "SH_REJECT_05"
    asrs_full     : "SH_REJECT_05"
    aisle 		  :
                    - name          : "SH_AISLE_L5"
                      level         :
                                      - "1"
                                      - "2"
                                      - "3"
                                      - "4"
                                      - "5"
                                      - "6"
                                      - "7"
                                      - "8"
                                      - "9"
                                      - "10"
                    - name          : "SH_AISLE_L6"
                      level         :
                                      - "1"
                                      - "2"
                                      - "3"
                                      - "4"
                                      - "5"
                                      - "6"
                                      - "7"
                                      - "8"
                                      - "9"
                                      - "10"
  887:
    process_key   : "Process_aisle_scanner_putaway"
    dim_fail      : "SH_REJECT_06"
    weigh_fail    : "SH_REJECT_06"
    other_fail    : "SH_REJECT_06"
    container_fail: "SH_REJECT_06"
    case_unknown  : "SH_REJECT_06"
    asrs_full     : "SH_REJECT_06"
    aisle 		  :
                    - name          : "SH_AISLE_U5"
                      level         :
                                      - "11"
                                      - "12"
                                      - "13"
                                      - "14"
                                      - "15"
                                      - "16"
                                      - "17"
                                      - "18"
                                      - "19"
                                      - "20"
                    - name          : "SH_AISLE_U6"
                      level         :
                                      - "11"
                                      - "12"
                                      - "13"
                                      - "14"
                                      - "15"
                                      - "16"
                                      - "17"
                                      - "18"
                                      - "19"
                                      - "20"
  885:
    process_key   : "Process_aisle_scanner_putaway"
    dim_fail      : "SH_REJECT_04"
    weigh_fail    : "SH_REJECT_04"
    other_fail    : "SH_REJECT_04"
    container_fail: "SH_REJECT_04"
    case_unknown  : "SH_REJECT_04"
    asrs_full     : "SH_REJECT_04"
    aisle 		  :
                    - name          : "SH_AISLE_U3"
                      level         :
                                      - "11"
                                      - "12"
                                      - "13"
                                      - "14"
                                      - "15"
                                      - "16"
                                      - "17"
                                      - "18"
                                      - "19"
                                      - "20"
                    - name          : "SH_AISLE_U4"
                      level         :
                                      - "11"
                                      - "12"
                                      - "13"
                                      - "14"
                                      - "15"
                                      - "16"
                                      - "17"
                                      - "18"
                                      - "19"
                                      - "20"
  884:
    process_key   : "Process_aisle_scanner_putaway"
    dim_fail      : "SH_REJECT_03"
    weigh_fail    : "SH_REJECT_03"
    other_fail    : "SH_REJECT_03"
    container_fail: "SH_REJECT_03"
    case_unknown  : "SH_REJECT_03"
    asrs_full     : "SH_REJECT_03"
    aisle 		  :
                    - name          : "SH_AISLE_L3"
                      level         :
                                      - "1"
                                      - "2"
                                      - "3"
                                      - "4"
                                      - "5"
                                      - "6"
                                      - "7"
                                      - "8"
                                      - "9"
                                      - "10"
                    - name          : "SH_AISLE_L4"
                      level         :
                                      - "1"
                                      - "2"
                                      - "3"
                                      - "4"
                                      - "5"
                                      - "6"
                                      - "7"
                                      - "8"
                                      - "9"
                                      - "10"
  882:
    process_key   : "Process_aisle_scanner_putaway"
    dim_fail      : "SH_REJECT_02"
    weigh_fail    : "SH_REJECT_02"
    other_fail    : "SH_REJECT_02"
    container_fail: "SH_REJECT_02"
    case_unknown  : "SH_REJECT_02"
    asrs_full     : "SH_REJECT_02"
    aisle 		  :
                    - name          : "SH_AISLE_U1"
                      level         :
                                      - "11"
                                      - "12"
                                      - "13"
                                      - "14"
                                      - "15"
                                      - "16"
                                      - "17"
                                      - "18"
                                      - "19"
                                      - "20"
                    - name          : "SH_AISLE_U2"
                      level         :
                                      - "11"
                                      - "12"
                                      - "13"
                                      - "14"
                                      - "15"
                                      - "16"
                                      - "17"
                                      - "18"
                                      - "19"
                                      - "20"
    
  881:
    process_key   : "Process_aisle_scanner_putaway"
    dim_fail      : "SH_REJECT_01"
    weigh_fail    : "SH_REJECT_01"
    other_fail    : "SH_REJECT_01"
    container_fail: "SH_REJECT_01"
    case_unknown  : "SH_REJECT_01"
    asrs_full     : "SH_REJECT_01"
    aisle 		  :
                    - name          : "SH_AISLE_L1"
                      level         :
                                      - "1"
                                      - "2"
                                      - "3"
                                      - "4"
                                      - "5"
                                      - "6"
                                      - "7"
                                      - "8"
                                      - "9"
                                      - "10"
                    - name          : "SH_AISLE_L2"
                      level         :
                                      - "1"
                                      - "2"
                                      - "3"
                                      - "4"
                                      - "5"
                                      - "6"
                                      - "7"
                                      - "8"
                                      - "9"
                                      - "10"
