--- 
scannerConfigurations: 
  301: 
    asrs_full: ASRS_FULL
    container_fail: ASRS_UNKN
    dim_fail: DIM_FAIL
    manual_depal: MANL_DEPAL
    other_fail: ASRS_UNKN
    pallet_expired: EXP_PALLET
    pallet_expiry_threshold: "10"
    pallet_unknown: ASRS_UNKN
    process_key: Process_Pallet_putaway
    recall_reject: RECALL_REJECT
    robo_depal: ROBO_DEPAL
    weigh_fail: WEIGH_FAIL
  880: 
    case_unknown: CASE_UNKN
    container_fail: SHUTTLE_REJECT
    dim_fail: DIM_FAIL
    other_fail: SHUTTLE_REJECT
    panda: PANDA
    process_key: Process_Case_putaway
    weigh_fail: WEIGH_FAIL
  881: 
    aisle: 
      - 
        level: 
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
          - "8"
          - "9"
          - "10"
        name: SH_AISLE_L1
      - 
        level: 
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
          - "8"
          - "9"
          - "10"
        name: SH_AISLE_L2
    asrs_full: SH_REJECT_01
    case_unknown: SH_REJECT_01
    container_fail: SH_REJECT_01
    dim_fail: SH_REJECT_01
    other_fail: SH_REJECT_01
    process_key: Process_aisle_scanner_putaway
    weigh_fail: SH_REJECT_01
  882: 
    aisle: 
      - 
        level: 
          - "11"
          - "12"
          - "13"
          - "14"
          - "15"
          - "16"
          - "17"
          - "18"
          - "19"
          - "20"
        name: SH_AISLE_U1
      - 
        level: 
          - "11"
          - "12"
          - "13"
          - "14"
          - "15"
          - "16"
          - "17"
          - "18"
          - "19"
          - "20"
        name: SH_AISLE_U2
    asrs_full: SH_REJECT_02
    case_unknown: SH_REJECT_02
    container_fail: SH_REJECT_02
    dim_fail: SH_REJECT_02
    other_fail: SH_REJECT_02
    process_key: Process_aisle_scanner_putaway
    weigh_fail: SH_REJECT_02
  884: 
    aisle: 
      - 
        level: 
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
          - "8"
          - "9"
          - "10"
        name: SH_AISLE_L3
      - 
        level: 
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
          - "8"
          - "9"
          - "10"
        name: SH_AISLE_L4
    asrs_full: SH_REJECT_03
    case_unknown: SH_REJECT_03
    container_fail: SH_REJECT_03
    dim_fail: SH_REJECT_03
    other_fail: SH_REJECT_03
    process_key: Process_aisle_scanner_putaway
    weigh_fail: SH_REJECT_03
  885: 
    aisle: 
      - 
        level: 
          - "11"
          - "12"
          - "13"
          - "14"
          - "15"
          - "16"
          - "17"
          - "18"
          - "19"
          - "20"
        name: SH_AISLE_U3
      - 
        level: 
          - "11"
          - "12"
          - "13"
          - "14"
          - "15"
          - "16"
          - "17"
          - "18"
          - "19"
          - "20"
        name: SH_AISLE_U4
    asrs_full: SH_REJECT_04
    case_unknown: SH_REJECT_04
    container_fail: SH_REJECT_04
    dim_fail: SH_REJECT_04
    other_fail: SH_REJECT_04
    process_key: Process_aisle_scanner_putaway
    weigh_fail: SH_REJECT_04
  886: 
    aisle: 
      - 
        level: 
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
          - "8"
          - "9"
          - "10"
        name: SH_AISLE_L5
      - 
        level: 
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
          - "8"
          - "9"
          - "10"
        name: SH_AISLE_L6
    asrs_full: SH_REJECT_05
    case_unknown: SH_REJECT_05
    container_fail: SH_REJECT_05
    dim_fail: SH_REJECT_05
    other_fail: SH_REJECT_05
    process_key: Process_aisle_scanner_putaway
    weigh_fail: SH_REJECT_05
  887: 
    aisle: 
      - 
        level: 
          - "11"
          - "12"
          - "13"
          - "14"
          - "15"
          - "16"
          - "17"
          - "18"
          - "19"
          - "20"
        name: SH_AISLE_U5
      - 
        level: 
          - "11"
          - "12"
          - "13"
          - "14"
          - "15"
          - "16"
          - "17"
          - "18"
          - "19"
          - "20"
        name: SH_AISLE_U6
    asrs_full: SH_REJECT_06
    case_unknown: SH_REJECT_06
    container_fail: SH_REJECT_06
    dim_fail: SH_REJECT_06
    other_fail: SH_REJECT_06
    process_key: Process_aisle_scanner_putaway
    weigh_fail: SH_REJECT_06
  889: 
    aisle: 
      - 
        level: 
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
          - "8"
          - "9"
          - "10"
        name: SH_AISLE_L7
      - 
        level: 
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
          - "8"
          - "9"
          - "10"
        name: SH_AISLE_L8
    asrs_full: SH_REJECT_07
    case_unknown: SH_REJECT_07
    container_fail: SH_REJECT_07
    dim_fail: SH_REJECT_07
    other_fail: SH_REJECT_07
    process_key: Process_aisle_scanner_putaway
    weigh_fail: SH_REJECT_07
  890: 
    aisle: 
      - 
        level: 
          - "11"
          - "12"
          - "13"
          - "14"
          - "15"
          - "16"
          - "17"
          - "18"
          - "19"
          - "20"
        name: SH_AISLE_U7
      - 
        level: 
          - "11"
          - "12"
          - "13"
          - "14"
          - "15"
          - "16"
          - "17"
          - "18"
          - "19"
          - "20"
        name: SH_AISLE_U8
    asrs_full: SH_REJECT_08
    case_unknown: SH_REJECT_08
    container_fail: SH_REJECT_08
    dim_fail: SH_REJECT_08
    other_fail: SH_REJECT_08
    process_key: Process_aisle_scanner_putaway
    weigh_fail: SH_REJECT_08
